### ISSUE TITLE
Image not loading after upload

### ISSUE THREAD

**Issue by jeshocarmel** [keichan34/phoenix_exfile_test_app#1]
Hi Keichan,

I just downloaded your sample application **phoenix_exfile_test_app** and used mariaex instead of postgres. I'm unable to view the uploaded image. I haven't changed any code apart from the mariaex configuration in mix.exs.  The file has been uploaded into the tmp folder though.

![test](https://cloud.githubusercontent.com/assets/13138007/17430034/9ca72228-5b24-11e6-8d52-0a06de7f7087.png)

**Comment by jeshocarmel** [comment]
Invalid Parameter - /phoenix_exfile_test_app-master

**Comment by keichan34** [comment]
Can you paste the error message that the server is reporting here?

**Comment by jeshocarmel** [comment]
```
[info] Sent 200 in 1667ms
[info] GET /attachments/bMwcpAvQ_Q1k07iJD92F5cImTNvlFvKGVCZ5JOIDn_I=/store/fill/100/100/8889141db61fbbceed81d1981c202c0253414bd5f0e21e97de20f67bc1cf/file.jpg
[debug] [exfile] opening file: %Exfile.File{backend: %Exfile.Backend{backend_mod: Exfile.Backend.FileSystem, backend_name: "store", directory: "d:/phoenix_exfile_test_app-master/tmp/store", hasher: Exfile.Hasher.Random, max_size: -1, meta: %{}, postprocessors: [], preprocessors: []}, backend_meta:
[info] GET /attachments/9iq3WNm0jLQpWfnD6rAqPvHxccEx9zxXDoMiIJMfVEI=/store/fill/100/100/ea4b0233d0f5d51a35bccb6cdbcfccf81ff9c68b058dfa4e2b6a6a07a8d3/file.jpg
[debug] [exfile] opening file: %Exfile.File{backend: %Exfile.Backend{backend_mod: Exfile.Backend.FileSystem, backend_name: "store", directory: "d:/phoenix_exfile_test_app-master/tmp/store", hasher: Exfile.Hasher.Random, max_size: -1, meta: %{}, postprocessors: [], preprocessors: []}, backend_meta:
**Invalid Parameter - /phoenix_exfile_testInvalid Parameter - /phoenix_exfile_test_app-master
_app-master**
[info] Sent 500 in 479ms
[info] Sent 500 in 125ms
[debug] Ignoring unmatched topic "rooms:null" in PhoenixExfileTestApp.UserSocket
```

FYI,  my development environment is windows

**Comment by keichan34** [comment]
Hm. Could be a windows compatibility problem. I'll investigate a bit more and get back to you.

**Comment by jeshocarmel** [comment]
okay . noted

**Comment by noma4i** [comment]
Probably Iv found culprit. Path.exand in windows should expand using `\` but joining remain root_path looks incorrect. So resulting path is `/some_where\here\one_more_level`

That's it. Btw running even Dev env for elixir on windows is a pure suicide. Consider using windows 10 ubuntu bash. [Nice blogpost at Microsoft](https://blogs.windows.com/buildingapps/2016/03/30/run-bash-on-ubuntu-on-windows/)

**Comment by keichan34** [comment]
I see. Thanks for figuring out what the problem was. I found this issue in elixir https://github.com/elixir-lang/elixir/issues/1236 that's similar -- it says that Erlang will automatically translate `/` to `\` when running in Windows, but maybe that doesn't work if the path separators are all mixed up?

Anyways, thanks for your help! I'll be closing this issue for now, but I eventually want to get it working, so I will leave the original issue on https://github.com/keichan34/exfile/issues/37 open until it's fixed.

**Comment by jeshocarmel** [comment]
thanks @keichan34 . awesome
